<?php
/**
 * @var \MageEasy\DevTools\Block\Header $block
 */

$pathHints = $block->getDevPathHintsStatus();
$lessCompilation = $block->getLessCompilationStatus();
$layoutLogger = $block->getIsLayoutLoggerEnabled();

$requestInfo = $block->getRequestInfo();

$website = $block->getWebsite();
$store = $this->getStore();

$cacheTypes = $block->getAvailableTypes();

?>

<?php if ($block->isNavigateToAdminEnabled() || $block->isCustomerLoginEnabled() && $block->getCustomers()): ?>
    <div class="container-developer-options">
        <div class="debug-toolkit">
            <div class="section">
                <div class="column action-toolbar">
                    <?php if ($block->isCustomerLoginEnabled() && $block->getCustomers()): ?>
                        <div class="container-customer-login" data-iscustomerauthenticated="<?= $block->isCustomerAuthenticated() ?>">
                            <select id="customer-login">
                                <option>
                                    Login with selected customer..
                                </option>
                                <?php foreach ($block->getCustomers() as $customer): ?>
                                    <option data-password="<?= $customer->password ?>" value="<?= $customer->email; ?>">
                                        <?= $customer->name; ?> | <?= $customer->email; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <form>
                                <?= $block->getBlockHtml("formkey") ?>
                                <input type="hidden" name="login[developer]" value="true">
                                <input name="login[username]" id="dev-login-username" type="email">
                                <input name="login[password]" id="dev-login-password" type="password">
                            </form>
                        </div>
                    <?php endif; ?>
                    <?php if ($block->isNavigateToAdminEnabled()): ?>
                        <div class="container-navigate-to-admin" >
                            <button id="navigate-to-admin" class="action primary" data-uri="<?= $block->getBaseUrl() . $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName(); ?>">Navigate to /<?= $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName(); ?></button>
                        </div>
                    <?php endif; ?>
                    <div class="toggle-switch-container">
                        <label>Toggle Path Hints</label>
                        <small>Enables the use of <a title="Click to append to the current url" class="template-hints-activate" data-pathintvalue="<?= $block->getPathHintsParameter() ?>"><?= '?templatehints=' . $block->getPathHintsParameter() ?></a></small>
                        <label class="toggle-switch">
                            <input type="checkbox" name="toggle_path_hints"/>
                            <div></div>
                        </label>
                    </div>
                    <div class="toggle-switch-container">
                        <label>Toggle Layout Logger</label>
                        <small>Layouts can be found in var/log/layouts</small>
                        <label class="toggle-switch">
                            <input type="checkbox" name="toggle_layout_logger"/>
                            <div></div>
                        </label>
                    </div>
                    <div class="toggle-switch-container">
                        <label>Toggle Client Side Less Compilation</label>
                        <small>Disable, to enable server side compilation</small>
                        <br>
                        <small>Setup upgrade and di compile commands must be run after</small>
                        <label class="toggle-switch">
                            <input type="checkbox" name="less_compilation"/>
                            <div></div>
                        </label>
                    </div>
                </div>
            </div>
            <hr>
            <div class="section cache-management">
                <p class="heading">Cache Management</p>

                <button id="refresh-cache" class="action primary">Refresh Cache</button>

                <div class="column-container">
                    <div class="column">
                        <?php foreach ($cacheTypes as $type): ?>
                            <div class="cache-item">
                                <button data-id="<?= $type->getId() ?>" class="action primary refresh-cache-single">Refresh</button>
                                <div class="toggle-switch-container">
                                    <label class="toggle-switch">
                                        <?php if($type->getStatus()): ?>
                                            <input type="checkbox" class="cache-type" name="<?= $type->getId() ?>" checked="true"/>
                                        <?php else: ?>
                                            <input type="checkbox" class="cache-type" name="<?= $type->getId() ?>"/>
                                        <?php endif; ?>

                                        <?php if($type->getInvalidated()): ?>
                                            <div class="invalidated" title="This cache item is invalidated and needs to be refreshed."></div>
                                        <?php else: ?>
                                            <div></div>
                                        <?php endif; ?>
                                    </label>
                                </div>
                                <span class="title" data-id="<?= $type->getId() ?>">
                                    <span><?= $type->getCacheType() ?></span>
                                    <small>(<?= $type->getId() ?>)</small>
                                </span>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <hr>
            <div class="section">
                <p class="heading">Store Information</p>
                <div class="column-container">
                    <div class="column">
                        <div class="container">
                            <p class="title">Website Id</p>
                            <small class="value"><?= $website->getId(); ?></small>
                        </div>
                        <div class="container">
                            <p class="title">Website Name</p>
                            <small class="value"><?= $website->getName() ?></small>
                        </div>
                        <div class="container">
                            <p class="title">Store Id</p>
                            <small class="value"><?= $store->getId() ?></small>
                        </div>
                    </div>
                    <div class="column">
                        <div class="container">
                            <p class="title">Store Name</p>
                            <small class="value"><?= $store->getName() ?></small>
                        </div>
                        <div class="container">
                            <p class="title">Store Code</p>
                            <small class="value"><?= $store->getCode(); ?></small>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="section">
                <p class="heading">Request Information</p>
                <div class="container" >
                    <p class="title"><?= $requestInfo["base_url"]["name"] ?></p>
                    <small class="value"><?= $requestInfo["base_url"]["value"] ?></small>
                </div>
                <div class="container" >
                    <p class="title"><?= $requestInfo["backend_url"]["name"] ?></p>
                    <small class="value"><?= $requestInfo["backend_url"]["value"] ?></small>
                </div>
                <div class="column-container">
                    <div class="column">
                        <div class="container" >
                            <p class="title"><?= $requestInfo["path_info"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["path_info"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["module_name"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["module_name"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["controller"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["controller"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["action"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["action"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["full_action"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["full_action"]["value"] ?></small>
                        </div>
                    </div>
                    <div class="column">
                        <div class="container" >
                            <p class="title"><?= $requestInfo["route"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["route"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["area"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["area"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["client_ip"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["client_ip"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["magento_version"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["magento_version"]["value"] ?></small>
                        </div>
                        <div class="container" >
                            <p class="title"><?= $requestInfo["mode"]["name"] ?></p>
                            <small class="value"><?= $requestInfo["mode"]["value"] ?></small>
                        </div>
                        <?php if(isset($requestInfo["before_forward"])): ?>
                            <div class="container" >
                                <p class="title"><?= $requestInfo["before_forward"]["name"] ?></p>
                                <small class="value"><?= $requestInfo["before_forward"]["value"] ?></small>
                            </div>
                        <?php endif; ?>
                        <?php if(isset($requestInfo["params"])): ?>
                            <div class="container" >
                                <p class="title"><?= $requestInfo["params"]["name"] ?></p>
                                <small class="value"><?= $requestInfo["params"]["value"] ?></small>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <hr>
            <div class="section">
                <p class="heading">Handles</p>
                <div class="column-container">
                    <div class="column">
                        <?php foreach ($block->getHandles() as $handle): ?>
                            <p class="handle-title"><?= $handle ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <span class="toggler">
            <img src="<?= $block->escapeHtml($block->getViewFileUrl('MageEasy_DevTools::images/settings.svg')); ?>" alt="nav">
        </span>
            <script>

                require(["jquery", "mage/url"], function($, url) {

                    $(document).ready(function () {

                        window.developer = {
                            pathhints: '<?php echo $pathHints; ?>',
                            lesscompilation: '<?php echo $lessCompilation; ?>',
                            layoutlogger: '<?php echo $layoutLogger; ?>',
                        };

                        if(window.developer.pathhints == "1")
                        {
                            jQuery("input[name='toggle_path_hints']").attr('checked', true);
                        }
                        else {
                            jQuery("input[name='toggle_path_hints']").attr('checked', false);
                        }

                        if(window.developer.lesscompilation == "client_side_compilation")
                        {
                            jQuery("input[name='less_compilation']").attr('checked', true);
                        }
                        else
                        {
                            jQuery("input[name='toggle_layout_logger']").attr('checked', false);
                        }

                        if(window.developer.layoutlogger == "1")
                        {
                            jQuery("input[name='toggle_layout_logger']").attr('checked', true);
                        }
                        else
                        {
                            jQuery("input[name='toggle_layout_logger']").attr('checked', false);
                        }
                    });
                });

            </script>
        </div>
    </div>
<?php endif; ?>
